remote_theme: sylhare/Type-on-Strap

baseurl: "/kubernetes-tutorials"
url: "https://sandeepnkulkarni.github.io/"

# --- Basic options --- #

# Name of website
title: Kubernetes Tutorials

# Short description of your site
description: Kubernetes Tutorials to get you started!

# Your name to show in the footer
author: Sandeep Kulkarni

# Blog
excerpt: false                                           # Or "truncate" (first 250 characters), "false" to disable
